ARG ENVOY_BUILD_IMAGE
FROM $ENVOY_BUILD_IMAGE

ARG BUILD_CMD

WORKDIR /envoy-sources

COPY . .

RUN yum update -y && \
    yum install -y \
    gcc \
    gcc-c++ 

RUN bash -c "bazel/setup_clang.sh /opt/llvm"
RUN bash -c "$BUILD_CMD"
