ARG ENVOY_BUILD_IMAGE
FROM $ENVOY_BUILD_IMAGE

ARG BUILD_CMD

WORKDIR /envoy-sources

COPY . .

RUN sudo add-apt-repository ppa:ubuntu-toolchain-r/test
RUN sudo apt-get update
RUN sudo apt-get install gcc-4.9
RUN sudo apt-get upgrade libstdc++6

RUN bash -c "bazel/setup_clang.sh /opt/llvm"
RUN bash -c "$BUILD_CMD"
