ARG ENVOY_BUILD_IMAGE
FROM $ENVOY_BUILD_IMAGE

ARG BUILD_CMD

WORKDIR /envoy-sources

COPY . .

RUN yum -y install centos-release-scl && \
 yum -y install devtoolset-6-gcc devtoolset-6-gcc-c++ && \
 update-alternatives --install /usr/bin/gcc-4.9 gcc-4.9 /opt/rh/devtoolset-3/root/usr/bin/gcc 10 && \
 update-alternatives --install /usr/bin/g++-4.9 g++-4.9 /opt/rh/devtoolset-3/root/usr/bin/g++ 10

RUN bash -c "bazel/setup_clang.sh /opt/llvm"
RUN bash -c "$BUILD_CMD"
