name: CI
on: 
  workflow_dispatch:
    inputs:
      envoyTag:
        description: 'envoy tag to build'
        type: string
        required: true
jobs:
  # build_envoy_alpine_amd64:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Checkout step
  #       id: checkout
  #       uses: actions/checkout@v2
      
  #     - name: make space
  #       run: |
  #         sudo rm -rf /usr/share/dotnet
  #         sudo rm -rf /opt/ghc
  #         sudo rm -rf "/usr/local/share/boost"

  #     - name: make build alpine
  #       run: make build/envoy
  #       env:
  #         GOOS: linux
  #         GOARCH: amd64
  #         ENVOY_DISTRO: alpine
  #         BUILD_ENVOY_FROM_SOURCES: true
  #         ENVOY_TAG: ${{ github.event.inputs.envoyTag }}

  #     - name: Zip artifact
  #       run: |
  #         if [[ -f build/artifacts-linux-amd64/envoy/envoy-${envoyTag#v}-alpine ]]; then  
  #             tar -czvf build/artifacts-linux-amd64/envoy/envoy-${envoyTag#v}-alpine.tar.gz build/artifacts-linux-amd64/envoy/envoy-${envoyTag#v}-alpine
  #         fi
  #       env:
  #         envoyTag: ${{ github.event.inputs.envoyTag }}
      
  #     - name: Save artifact
  #       uses: actions/upload-artifact@v3
  #       id: save_artifacts
  #       with:
  #         name: artifacts
  #         path: |
  #           build/**/envoy/*.tar.gz

  # build_envoy_centos_amd64:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - name: Checkout step
  #       id: checkout
  #       uses: actions/checkout@v2

  #     # Hacky solution to resolve running out of disk space
  #     # https://github.com/actions/virtual-environments/issues/2840#issuecomment-790492173
  #     - name: make space
  #       run: |
  #         sudo rm -rf /usr/share/dotnet
  #         sudo rm -rf /opt/ghc
  #         sudo rm -rf "/usr/local/share/boost"

  #     - name: make build centos
  #       run: make build/envoy
  #       env:
  #         GOOS: linux
  #         GOARCH: amd64
  #         ENVOY_DISTRO: centos
  #         BUILD_ENVOY_FROM_SOURCES: true
  #         ENVOY_TAG: ${{ github.event.inputs.envoyTag }}
      
  #     - name: Zip artifact
  #       run: |
  #         if [[ -f build/artifacts-linux-amd64/envoy/envoy-${envoyTag#v}-centos ]]; then  
  #             tar -czvf build/artifacts-linux-amd64/envoy/envoy-${envoyTag#v}-centos.tar.gz build/artifacts-linux-amd64/envoy/envoy-${envoyTag#v}-centos
  #         fi
  #       env:
  #         envoyTag: ${{ github.event.inputs.envoyTag }}
      
  #     - name: Save artifact
  #       uses: actions/upload-artifact@v3
  #       id: save_artifacts
  #       with:
  #         name: artifacts
  #         path: |
  #           build/**/envoy/*.tar.gz

  build_envoy_darwin_amd64:
    runs-on: macos-latest
    steps:
      - name: Checkout step
        id: checkout
        uses: actions/checkout@v2

      - name: install
        run: brew install coreutils

      - name: make build alpine
        run: make build/envoy
        env:
          GOOS: darwin
          GOARCH: amd64
          ENVOY_DISTRO: darwin
          BUILD_ENVOY_FROM_SOURCES: true
          ENVOY_TAG: ${{ github.event.inputs.envoyTag }}

      - name: Zip artifact
        run: |
          if [[ -f build/artifacts-darwin-amd64/envoy/envoy-${envoyTag#v}-darwin ]]; then  
              tar -czvf build/artifacts-darwin-amd64/envoy/envoy-${envoyTag#v}-darwin.tar.gz build/artifacts-darwin-amd64/envoy/envoy-${envoyTag#v}-darwin
          fi
        env:
          envoyTag: ${{ github.event.inputs.envoyTag }}
      
      - name: Save artifact
        uses: actions/upload-artifact@v3
        id: save_artifacts
        with:
          name: artifacts
          path: |
            build/**/envoy/*.tar.gz