name: CI
on: workflow_dispatch
jobs:
  build_envoy_alpine_amd64:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout step
        id: checkout
        uses: actions/checkout@v2

      - name: make build alpine
        run: make build/envoy
        env:
          GOOS: linux
          GOARCH: amd64
          ENVOY_DISTRO: alpine
      
      - name: Save artifact
        uses: actions/upload-artifact@v3
        id: save_artifacts
        with:
          name: artifacts
          path: |
            build/**/envoy