name: CI
on: workflow_dispatch
jobs:
  build:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-18.04
    env:
      OS: linux
      ARCH: amd64
      ENVOY_DISTRO: linux

    steps:
      #Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v3
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: checkout envoy
        run: |
          mkdir -p artifacts
          git clone -n https://github.com/envoyproxy/envoy.git
          git checkout release/v1.22

      - name: build envoy
        env:
          IMAGE_NAME: envoyproxy/envoy-build-ubuntu
        run: |
          ENVOY_DOCKER_BUILD_DIR=${GITHUB_WORKSPACE}/artifacts ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release.server_only'

      - name: inspect
        run:  tree .

      - name: Save artifact
        if: hashFiles('artifacts/') != ''
        uses: actions/upload-artifact@v3
        id: save_artifacts
        with:
          name: artifacts
          path: artifacts