name: CI

on: [push, pull_request]

jobs:
  test:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04
    env:
      OS: linux
      ARCH: amd64
      ENVOY_DISTRO: linux
      ENVOY_TAG: b16d390f11376e47f479778f2362ea4f48bdc895

    steps:
      # Caches and restores the bazelisk download directory, the bazel build directory.
      - name: Cache bazel
        uses: actions/cache@v2.1.4
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}

      # Checks-out your repository under $GITHUB_WORKSPACE, which is the CWD for
      # the rest of the steps
      - uses: actions/checkout@v2
      - name: build envoy
        run: |
          mkdir -p build/envoy-sources
          cd build/envoy-sources
          git clone https://github.com/envoyproxy/envoy.git
          git checkout $ENVOY_TAG
          docker run -v `pwd`:/src/envoy -w /src/envoy envoyproxy/envoy-build-ubuntu -- ./ci/run_envoy_docker.sh './ci/do_ci.sh bazel.release'
