name: test
on: workflow_dispatch
jobs:
  build:
    # virtual environments: https://github.com/actions/virtual-environments
    runs-on: ubuntu-18.04
    env:
      OS: linux
      ARCH: amd64
      ENVOY_DISTRO: linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: test
        run: echo "testing dispatch"
