name: Test
on: 
  workflow_dispatch:
jobs:
  build:
    strategy:
      max-parallel: 2
      matrix:
        distro: [darwin, centos]
        experimental: [false]
        include:
          - distro: alpine
            experimental: true
    runs-on: ubuntu-latest
    continue-on-error: ${{matrix.experimental}}
    steps:

    - name: Print
      run: |
        echo ${{matrix.distro}}
        exit 1

        
  notify:
    name: Slack Notification
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get aggregate Workflow status
        id: out
        uses: technote-space/workflow-conclusion-action@v3

      - name: inspect env
        run: |
          echo ${{ env.WORKFLOW_CONCLUSION }}
