name: Test
on: 
  workflow_dispatch:
jobs:
  build:
    strategy:
      max-parallel: 2
      matrix:
        distro: [darwin, centos]
        include:
          - distro: alpine
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:

    - name: Print
      run: |
        echo ${{matrix.distro}}
        sleep 3
